version: "3.8"

networks:
  microservice-net:
    driver: overlay
    attachable: true   # permet aux conteneurs de test de se connecter facilement

services:

  # Eureka Service (Registry)
  eureka-service:
    image: houssemsouid/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - microservice-net
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  # API Gateway
  gateway:
    image: houssemsouid/gateway:latest
    ports:
      - "8888:8888"
    networks:
      - microservice-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  # Product Service
  product-service:
    image: houssemsouid/product-service:latest
    networks:
      - microservice-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  # Billing Service
  billing-service:
    image: houssemsouid/billing-service:latest
    networks:
      - microservice-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  # Billing Producer
  billing-producer:
    image: houssemsouid/billing-producer:latest
    networks:
      - microservice-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  # Analyse Service
  analyse-service:
    image: houssemsouid/analyse-service:latest
    networks:
      - microservice-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  # Customer Service
  custmer-service:     # ⚠️ attention à l’orthographe "custmer" (pas "customer")
    image: houssemsouid/custmer-service:latest
    networks:
      - microservice-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  # Frontend (Angular)
  frontend:
    image: houssemsouid/frontend:latest
    ports:
      - "4200:80"
    networks:
      - microservice-net
    depends_on:
      - gateway
    deploy:
      replicas: 1
      restart_policy:
        condition: any
